### ISSUE TITLE
MàJ démo kubernetes

### ISSUE THREAD

**Issue by pyaillet** [ebriand/falco-demo#3]
Pour la démo kubernetes, est-ce qu'on met simplement à jour pour passer par falco-sidekick et afficher les errors dans falco-sidekick-ui ?
Ou est-ce que tu pensais ajouter plus de choses (genre passer par Kubeless ou OpenFaas) ?

**Comment by ebriand** [comment]
C'est une bonne question... Pour la démo je sais pas si ça va apporter quelque chose effectivement de mettre en place tout ce qu'il faut pour faire de l'appel de fonction.

J'ai testé le setup qui se trouve dans la série d'article de blog sur le response engine (https://falco.org/blog/falcosidekick-reponse-engine-part-3-knative/) et au final je suis pas persuadé de l'intérêt en démo... (en "vrai" par contre je dirai pas la même chose 😛 )

Donc même si je pensais ajouter plein de choses, je pense que rester sur notre "response engine" ça suffira 🙂

**Comment by pyaillet** [comment]
Ok, donc, chart falco avec falco-sidekick qui envoie vers falco-sidekick-ui et notre response-engine ?
Je peux regarder pour faire ça de mon côté si tu veux.

**Comment by ebriand** [comment]
Ca marche, merci 👍

**Comment by pyaillet** [comment]
Closed by #4
